### ISSUE TITLE
Show some web socket PV data on the details page when first loaded

### ISSUE THREAD

**Issue by tynanford** [ChannelFinder/pvinfo#3]
Things like HIHI/HIGH/LOW/LOLO etc could be fetched and shown. Or we could just turn on pvws monitoring on the details page automatically. Maybe make that a configuration option

**Comment by mitchfrauenheim** [comment]
Just pre-load the black values

**Comment by tynanford** [comment]
@mitchfrauenheim for this one let's just default the checkbox on the PV details page to on. Based on feedback from users I think this makes more sense. Maybe we can explore a timeout on the websocket to avoid issues with tabs staying open forever
